from __future__ import annotations

import sys
from pathlib import Path as _BootstrapPath
sys.path.insert(0, str(_BootstrapPath(__file__).resolve().parents[1]))

import argparse
import json
import os
import statistics
import time
from collections import Counter, defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from common import (
    append_jsonl,
    call_with_retry,
    image_data_url,
    load_jsonl,
    openai_pydantic_call,
    resolve_asset,
    select_items,
    write_json,
)
from prompts import benchmark_task_text


class JudgeResult(BaseModel):
    score: Literal[0, 1, 2, 3]
    verdict: Literal[
        "fully_correct",
        "mostly_correct",
        "partially_correct",
        "incorrect",
        "unjudgeable",
    ]
    matches_reference_solution: bool
    alternative_valid_solution: bool
    confidence: float = Field(ge=0.0, le=1.0)
    reason: str
    failure_tags: list[str]
    needs_human_review: bool
    review_reason: str | None


JUDGE_SYSTEM_PROMPT = """You are a strict judge for a visual-reasoning image-generation benchmark.

You will see a problem image, one known correct reference answer image, a candidate answer image generated by the tested model, and an optional textual explanation from the candidate model.

Core principles:
1. The reference answer is only one known valid solution and does not imply uniqueness. Do not mark a candidate wrong merely because its pixels, layout, or visual appearance differ from the reference.
2. First understand the task constraints, then judge whether the candidate image is an independently valid answer. For pattern-completion tasks, the rule used by the candidate must consistently explain the given relations; it must not be an ad hoc rule made only for the candidate or depend on unnecessary exceptions. For spatial tasks, check the actual geometric, projection, folding, adjacency, orientation, assembly, and cross-section constraints.
3. If the candidate differs from the reference but satisfies another reasonable, unified, simple, and complete rule or spatial constraint, assign score=3, set alternative_valid_solution=true, and set needs_human_review=true for manual confirmation of the new solution.
4. The candidate textual explanation is only supporting evidence. The final score must be based on the candidate image; a correct explanation cannot compensate for an incorrect image. Do not require the candidate image to contain textual explanations.
5. Do not treat style, line width, minor scaling, or minor translation as reasoning errors unless they affect the answer structure or readability.

Four-level scoring:
3 = Fully correct: satisfies the core constraints of a valid solution; reasonable alternative valid solutions are allowed.
2 = Mostly correct: the core reasoning direction is correct, with only a few local errors, and the intended correct solution is still clear.
1 = Partially correct: contains a few correct features, but has key structural or logical errors and cannot serve as a valid answer.
0 = Incorrect: violates the task, is severely unreadable, blank, irrelevant, or cannot complete the required task.

Give a brief justification grounded in observable visual evidence. Do not output a long chain of thought."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate generated benchmark images with GPT-5.5-family judges.")
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--run", type=Path, required=True, help="Run directory created by generate.py.")
    parser.add_argument("--judge-model", default="gpt-5.5")
    parser.add_argument("--reasoning-effort", choices=["none", "low", "medium", "high", "xhigh"], default="high")
    parser.add_argument("--passes", type=int, default=1, help="Independent judge passes per item; use 2 for final benchmark runs.")
    parser.add_argument("--confidence-threshold", type=float, default=0.70)
    parser.add_argument("--start-id", default=None)
    parser.add_argument("--end-id", default=None)
    parser.add_argument("--ids", default=None)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--max-retries", type=int, default=3)
    parser.add_argument("--retry-delay", type=float, default=2.0)
    parser.add_argument("--request-timeout", type=float, default=180.0)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def load_generation_records(run_dir: Path) -> dict[str, dict[str, Any]]:
    records_path = run_dir / "records.jsonl"
    latest: dict[str, dict[str, Any]] = {}
    if records_path.exists():
        for row in load_jsonl(records_path):
            latest[str(row["id"])] = row
    return latest


def existing_eval_ids(path: Path) -> set[str]:
    if not path.exists():
        return set()
    ok: set[str] = set()
    for row in load_jsonl(path):
        if row.get("status") == "success":
            ok.add(str(row["id"]))
    return ok


def filter_items_for_run(items: list[dict[str, Any]], run_dir: Path) -> list[dict[str, Any]]:
    config_path = run_dir / "config.json"
    if not config_path.exists():
        return items
    try:
        task = json.loads(config_path.read_text(encoding="utf-8")).get("task")
    except Exception:
        return items
    if task == "figure_completion":
        return [item for item in items if int(str(item["id"])) <= 394]
    if task == "spatial_generation":
        return [item for item in items if int(str(item["id"])) >= 395]
    return items


def mode_score(scores: list[int]) -> int:
    counts = Counter(scores)
    max_count = max(counts.values())
    tied = [score for score, count in counts.items() if count == max_count]
    return min(tied)  # Conservative tie break.


def aggregate_passes(results: list[JudgeResult], confidence_threshold: float) -> dict[str, Any]:
    scores = [r.score for r in results]
    final_score = mode_score(scores)
    confidence = statistics.mean(r.confidence for r in results)
    alternative = any(r.alternative_valid_solution for r in results)
    disagreement = max(scores) - min(scores) if len(scores) > 1 else 0
    needs_review = (
        alternative
        or confidence < confidence_threshold
        or disagreement >= 2
        or any(r.needs_human_review for r in results)
    )
    review_reasons = [r.review_reason for r in results if r.review_reason]
    if disagreement >= 2:
        review_reasons.append(f"judge score disagreement: {scores}")
    if confidence < confidence_threshold:
        review_reasons.append(f"mean confidence {confidence:.2f} below threshold")

    representative = next((r for r in results if r.score == final_score), results[0])
    return {
        "score": final_score,
        "normalized_score": round(final_score / 3 * 100, 2),
        "verdict": representative.verdict,
        "matches_reference_solution": all(r.matches_reference_solution for r in results),
        "alternative_valid_solution": alternative,
        "confidence": round(confidence, 4),
        "reason": representative.reason,
        "failure_tags": sorted({tag for r in results for tag in r.failure_tags}),
        "needs_human_review": needs_review,
        "review_reason": "; ".join(dict.fromkeys(review_reasons)) or None,
        "judge_passes": [r.model_dump() for r in results],
    }


def summarize(rows: list[dict[str, Any]]) -> dict[str, Any]:
    successful = [r for r in rows if r.get("status") == "success"]
    failed = [r for r in rows if r.get("status") != "success"]

    def summarize_subset(subset: list[dict[str, Any]]) -> dict[str, Any]:
        if not subset:
            return {"count": 0}
        scores = [int(r["score"]) for r in subset]
        dist = Counter(scores)
        return {
            "count": len(subset),
            "valid_at_1": round(sum(s == 3 for s in scores) / len(scores), 6),
            "mean_tier": round(statistics.mean(scores), 4),
            "normalized_score": round(statistics.mean(scores) / 3 * 100, 4),
            "score_distribution": {str(k): dist.get(k, 0) for k in [0, 1, 2, 3]},
            "human_review_count": sum(bool(r.get("needs_human_review")) for r in subset),
            "alternative_solution_count": sum(bool(r.get("alternative_valid_solution")) for r in subset),
        }

    by_group: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in successful:
        by_group[str(row.get("group", "unknown"))].append(row)

    return {
        "evaluated_successfully": len(successful),
        "evaluation_failures": len(failed),
        "overall": summarize_subset(successful),
        "by_group": {group: summarize_subset(group_rows) for group, group_rows in sorted(by_group.items())},
    }


def main() -> None:
    args = parse_args()
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OPENAI_API_KEY is not set")
    if args.passes < 1:
        raise ValueError("--passes must be >= 1")

    try:
        from openai import OpenAI
    except ImportError as exc:
        raise RuntimeError("Install dependencies: pip install -r requirements.txt") from exc

    client = OpenAI(timeout=args.request_timeout)
    dataset_root = args.dataset.resolve()
    run_dir = args.run.resolve()
    items = load_jsonl(dataset_root / "data.jsonl")
    items = filter_items_for_run(items, run_dir)
    requested_ids = set(args.ids.split(",")) if args.ids else None
    items = select_items(items, args.start_id, args.end_id, requested_ids, args.limit)
    selected_item_ids = {str(item["id"]) for item in items}
    generations = load_generation_records(run_dir)

    eval_dir = run_dir / "evaluation" / args.judge_model.replace("/", "_")
    eval_dir.mkdir(parents=True, exist_ok=True)
    results_path = eval_dir / "results.jsonl"
    review_path = eval_dir / "human_review.jsonl"
    done = set() if args.overwrite else existing_eval_ids(results_path)
    pending = [item for item in items if str(item["id"]) not in done]

    write_json(
        eval_dir / "config.json",
        {
            "created_at": datetime.now(timezone.utc).isoformat(),
            "dataset": str(dataset_root),
            "run": str(run_dir),
            "judge_model": args.judge_model,
            "reasoning_effort": args.reasoning_effort,
            "passes": args.passes,
            "confidence_threshold": args.confidence_threshold,
            "selected_count": len(items),
            "pending_count_at_start": len(pending),
        },
    )

    def judge_once(item: dict[str, Any], candidate_path: Path, explanation: str | None) -> JudgeResult:
        question_path = resolve_asset(dataset_root, str(item["image"]))
        reference_path = resolve_asset(dataset_root, str(item["answer"]))
        task_text = benchmark_task_text(item)
        candidate_explanation = explanation or "(no textual explanation)"
        user_text = (
            f"Task: {task_text}\n"
            "The following inputs are provided in order: the problem image, one known correct reference answer image, and the candidate generated answer image.\n"
            f"Optional textual explanation from the candidate model: {candidate_explanation}"
        )
        content: list[dict[str, Any]] = [
            {"type": "input_text", "text": user_text + "\n[Problem image]"},
            {"type": "input_image", "image_url": image_data_url(question_path), "detail": "original"},
            {"type": "input_text", "text": "[Known reference answer image: one known valid solution, not necessarily unique]"},
            {"type": "input_image", "image_url": image_data_url(reference_path), "detail": "original"},
            {"type": "input_text", "text": "[Candidate generated answer image: score this image]"},
            {"type": "input_image", "image_url": image_data_url(candidate_path), "detail": "original"},
        ]

        return openai_pydantic_call(
            client,
            model=args.judge_model,
            reasoning_effort=args.reasoning_effort,
            input_messages=[
                {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                {"role": "user", "content": content},
            ],
            output_model=JudgeResult,
            schema_name="civil_service_eval",
        )

    def evaluate_one(item: dict[str, Any]) -> dict[str, Any]:
        item_id = str(item["id"])
        started = time.perf_counter()
        generation = generations.get(item_id, {})
        candidate_path = run_dir / "images" / f"{item_id}.png"
        if generation.get("status") != "success" or not candidate_path.is_file():
            return {
                "id": item_id,
                "status": "error",
                "error": "missing successful generation record or candidate image",
                "group": "spatial_generation" if item.get("prompt") else "missing_figure",
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }

        try:
            passes: list[JudgeResult] = []
            for _ in range(args.passes):
                result = call_with_retry(
                    lambda: judge_once(item, candidate_path, generation.get("explanation")),
                    max_retries=args.max_retries,
                    base_delay=args.retry_delay,
                )
                passes.append(result)
            aggregate = aggregate_passes(passes, args.confidence_threshold)
            return {
                "id": item_id,
                "status": "success",
                "group": "spatial_generation" if item.get("prompt") else "missing_figure",
                "judge_model": args.judge_model,
                **aggregate,
                "latency_seconds": round(time.perf_counter() - started, 3),
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }
        except Exception as exc:
            return {
                "id": item_id,
                "status": "error",
                "group": "spatial_generation" if item.get("prompt") else "missing_figure",
                "error": f"{type(exc).__name__}: {exc}",
                "latency_seconds": round(time.perf_counter() - started, 3),
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }

    completed = 0
    new_rows: list[dict[str, Any]] = []
    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as pool:
        futures = {pool.submit(evaluate_one, item): str(item["id"]) for item in pending}
        for future in as_completed(futures):
            row = future.result()
            append_jsonl(results_path, row)
            if row.get("status") == "success" and row.get("needs_human_review"):
                append_jsonl(review_path, row)
            new_rows.append(row)
            completed += 1
            score_text = row.get("score", "-")
            print(f"[{completed}/{len(pending)}] {row['id']} {row['status']} score={score_text}")

    all_rows = load_jsonl(results_path) if results_path.exists() else []
    # Keep the latest record per ID if the user intentionally reruns with --overwrite.
    latest: dict[str, dict[str, Any]] = {
        str(r["id"]): r for r in all_rows
        if str(r["id"]) in selected_item_ids
    }
    summary = summarize(list(latest.values()))
    summary["judge_model"] = args.judge_model
    summary["run"] = str(run_dir)
    write_json(eval_dir / "summary.json", summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"Evaluation complete: {eval_dir}")


if __name__ == "__main__":
    main()
