from __future__ import annotations

import sys
from pathlib import Path as _BootstrapPath
sys.path.insert(0, str(_BootstrapPath(__file__).resolve().parents[1]))

import argparse
import os
import statistics
import threading
import time
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from common import (
    append_jsonl,
    call_with_retry,
    image_data_url,
    latest_records,
    load_jsonl,
    openai_pydantic_call,
    resolve_asset,
    select_items,
    write_json,
)


class MazeJudgeResult(BaseModel):
    score: Literal[0, 1, 2, 3]
    route_visible: bool = False
    starts_at_entrance: bool = False
    reaches_exit: bool = False
    path_continuous: bool = False
    original_canvas_preserved: bool = True
    redrawn_or_perspective_changed: bool = False
    maze_structure_preserved: bool = True
    wall_collisions: int = Field(default=0, ge=0)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    reason: str = ""
    needs_human_review: bool = False
    review_reason: str | None = None


JUDGE_SYSTEM_PROMPT = """You are a strict evaluator for a visual maze benchmark.

You will see three images in a fixed order:
1. The original maze problem image.
2. One known correct reference answer image.
3. The candidate answer image generated by the model.

First perform a fidelity check, then perform a path check. The score must be based on whether the candidate image solves the maze in the original problem image, not a maze that the candidate has modified or redrawn.

Fidelity hard rules:
- The candidate image should look like the red path was directly overlaid on the original problem image. The original canvas ratio, viewpoint, boundary, black wall positions and shapes, entrance arrow, and destination icon should be largely unchanged.
- If the candidate redraws the maze as a photo, paper sheet, perspective view, hand-drawn style, 3D style, new layout, or clearly changes the size, crop, rotation, or projection, set original_canvas_preserved=false and redrawn_or_perspective_changed=true, and cap the score at 1.
- If the candidate moves, deletes, adds, stretches, disconnects, or modifies key walls so that the path becomes easier to justify in the altered maze, set maze_structure_preserved=false and cap the score at 1; assign 0 for severe cases.
- Minor compression, antialiasing, line-width, or color differences are acceptable, but they must not change maze topology or spatial relations.

Path hard rules:
- The path must start from the entrance in the original problem image and reach the destination in the original problem image.
- The path must be continuous, clear, and always remain inside the corridors of the original maze.
- Any visible crossing through black walls, jump, break, failure to reach the destination, or wrong starting point prevents a score of 3.
- The reference answer is only one known valid route and is not unique; the candidate route may differ, but it must be valid on the unmodified original maze.
- The candidate model's textual explanation is only supporting evidence and cannot compensate for errors in the image.

Four-level scoring:
3 = Fully correct: the candidate preserves the original canvas and maze structure, adds only a red path, and the path is continuous from entrance to destination without crossing walls.
2 = Mostly correct: the original structure is preserved and the route is mostly valid, with only one very small local drawing ambiguity or minor error; there must be no obvious wall crossing, break, missed destination, or structural drift.
1 = Partially correct: there is a visible solving attempt, but with multiple wall crossings, an obviously incomplete route, wrong endpoints, or redrawing/perspective/structural drift while still being roughly related to the original problem.
0 = Incorrect: no recognizable route, irrelevant output, severe destruction or replacement of the maze, unjudgeable output, or an answer mainly drawn on another maze.

Field requirements:
- original_canvas_preserved indicates whether the candidate preserves the canvas, viewpoint, and main visual layout of the original problem image.
- redrawn_or_perspective_changed indicates whether the candidate was redrawn, photo-like, perspectivized, stylized, or relaid out.
- maze_structure_preserved indicates whether the black-wall topology and key positions are preserved.
- wall_collisions estimates how many times the red path crosses original black walls.

Output only structured scoring fields and a brief reason. Do not output a long chain of thought."""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate maze generations with a multimodal judge.")
    parser.add_argument("--dataset", type=Path, required=True, help="One difficulty directory, e.g. maze_benchmark_v1/beginner")
    parser.add_argument("--run", type=Path, required=True)
    parser.add_argument("--judge-model", default="gpt-5.5")
    parser.add_argument("--reasoning-effort", choices=["none", "low", "medium", "high", "xhigh"], default="high")
    parser.add_argument("--passes", type=int, default=1)
    parser.add_argument("--confidence-threshold", type=float, default=0.70)
    parser.add_argument("--start-id", default=None)
    parser.add_argument("--end-id", default=None)
    parser.add_argument("--ids", default=None)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--max-retries", type=int, default=3)
    parser.add_argument("--retry-delay", type=float, default=2.0)
    parser.add_argument("--request-timeout", type=float, default=180.0)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def mode_score(scores: list[int]) -> int:
    counts = Counter(scores)
    max_count = max(counts.values())
    return min(score for score, count in counts.items() if count == max_count)


def aggregate(results: list[MazeJudgeResult], confidence_threshold: float) -> dict[str, Any]:
    scores = [r.score for r in results]
    raw_score = mode_score(scores)
    representative = next(r for r in results if r.score == raw_score)
    confidence = statistics.mean(r.confidence for r in results)
    disagreement = max(scores) - min(scores) if len(scores) > 1 else 0
    canvas_failed = any(not r.original_canvas_preserved for r in results)
    redrawn = any(r.redrawn_or_perspective_changed for r in results)
    structure_failed = any(not r.maze_structure_preserved for r in results)
    capped_by_fidelity = canvas_failed or redrawn or structure_failed
    final_score = min(raw_score, 1) if capped_by_fidelity else raw_score
    needs_review = (
        confidence < confidence_threshold
        or disagreement >= 2
        or any(r.needs_human_review for r in results)
        or capped_by_fidelity
    )
    reasons = [r.review_reason for r in results if r.review_reason]
    if confidence < confidence_threshold:
        reasons.append(f"mean confidence {confidence:.2f} below threshold")
    if disagreement >= 2:
        reasons.append(f"judge score disagreement: {scores}")
    if capped_by_fidelity:
        reasons.append("score capped because candidate did not preserve the original maze canvas/structure")
    return {
        "score": final_score,
        "normalized_score": round(final_score / 3 * 100, 2),
        "raw_judge_score": raw_score,
        "route_visible": representative.route_visible,
        "starts_at_entrance": representative.starts_at_entrance,
        "reaches_exit": representative.reaches_exit,
        "path_continuous": representative.path_continuous,
        "original_canvas_preserved": not canvas_failed,
        "redrawn_or_perspective_changed": redrawn,
        "maze_structure_preserved": not structure_failed,
        "wall_collisions": representative.wall_collisions,
        "confidence": round(confidence, 4),
        "reason": representative.reason,
        "needs_human_review": needs_review,
        "review_reason": "; ".join(dict.fromkeys(reasons)) or None,
        "judge_passes": [r.model_dump() for r in results],
    }


def summarize(rows: list[dict[str, Any]]) -> dict[str, Any]:
    ok = [r for r in rows if r.get("status") == "success"]
    failed = [r for r in rows if r.get("status") != "success"]
    if not ok:
        return {"evaluated_successfully": 0, "evaluation_failures": len(failed)}
    scores = [int(r["score"]) for r in ok]
    dist = Counter(scores)
    return {
        "evaluated_successfully": len(ok),
        "evaluation_failures": len(failed),
        "solve_at_1": round(sum(s == 3 for s in scores) / len(scores), 6),
        "mean_tier": round(statistics.mean(scores), 4),
        "normalized_score": round(statistics.mean(scores) / 3 * 100, 4),
        "score_distribution": {str(k): dist.get(k, 0) for k in [0, 1, 2, 3]},
        "starts_at_entrance_rate": round(statistics.mean(bool(r["starts_at_entrance"]) for r in ok), 6),
        "reaches_exit_rate": round(statistics.mean(bool(r["reaches_exit"]) for r in ok), 6),
        "continuous_path_rate": round(statistics.mean(bool(r["path_continuous"]) for r in ok), 6),
        "structure_preserved_rate": round(statistics.mean(bool(r["maze_structure_preserved"]) for r in ok), 6),
        "original_canvas_preserved_rate": round(
            statistics.mean(bool(r.get("original_canvas_preserved", True)) for r in ok),
            6,
        ),
        "redrawn_or_perspective_changed_count": sum(
            bool(r.get("redrawn_or_perspective_changed", False)) for r in ok
        ),
        "zero_collision_rate": round(statistics.mean(int(r["wall_collisions"]) == 0 for r in ok), 6),
        "human_review_count": sum(bool(r.get("needs_human_review")) for r in ok),
    }


def main() -> None:
    args = parse_args()
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OPENAI_API_KEY is not set")
    if args.passes < 1 or args.workers < 1:
        raise ValueError("--passes and --workers must be >= 1")

    try:
        from openai import OpenAI
    except ImportError as exc:
        raise RuntimeError("Install dependencies: pip install -r requirements.txt") from exc

    client = OpenAI(
        **({"base_url": os.environ["OPENAI_BASE_URL"]} if os.getenv("OPENAI_BASE_URL") else {}),
        timeout=args.request_timeout,
    )
    dataset_root = args.dataset.resolve()
    run_dir = args.run.resolve()
    items = load_jsonl(dataset_root / "data.jsonl")
    requested_ids = set(args.ids.split(",")) if args.ids else None
    items = select_items(items, args.start_id, args.end_id, requested_ids, args.limit)
    generations = latest_records(run_dir / "records.jsonl")

    eval_dir = run_dir / "evaluation" / f"maze_{args.judge_model.replace('/', '_')}"
    eval_dir.mkdir(parents=True, exist_ok=True)
    results_path = eval_dir / "results.jsonl"
    review_path = eval_dir / "human_review.jsonl"
    if args.overwrite:
        for path in (results_path, review_path):
            if path.exists():
                path.unlink()
    done = set() if args.overwrite else {
        str(r["id"]) for r in load_jsonl(results_path) if r.get("status") == "success"
    } if results_path.exists() else set()
    pending = [item for item in items if str(item["id"]) not in done]

    write_json(eval_dir / "config.json", {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "dataset": str(dataset_root),
        "run": str(run_dir),
        "judge_model": args.judge_model,
        "reasoning_effort": args.reasoning_effort,
        "passes": args.passes,
        "confidence_threshold": args.confidence_threshold,
        "selected_count": len(items),
    })

    write_lock = threading.Lock()

    def judge_once(item: dict[str, Any], candidate_path: Path, explanation: str | None) -> MazeJudgeResult:
        question_path = resolve_asset(dataset_root, str(item["image"]))
        reference_path = resolve_asset(dataset_root, str(item["answer"]))
        user_text = (
            "The following inputs are provided in order: the original maze problem image, one known correct reference answer image, and the candidate generated answer image.\n"
            f"Optional textual description from the candidate model: {explanation or '(none)'}\n"
            "First compare whether the candidate preserves the canvas, viewpoint, and black maze-wall structure of the original problem image, "
            "then judge whether the red path legally reaches the destination from the entrance on the original maze."
        )
        content: list[dict[str, Any]] = [
            {"type": "input_text", "text": user_text + "\n[Original maze problem image]"},
            {"type": "input_image", "image_url": image_data_url(question_path), "detail": "original"},
            {"type": "input_text", "text": "[Known correct reference answer image: only one valid route, not necessarily unique]"},
            {"type": "input_image", "image_url": image_data_url(reference_path), "detail": "original"},
            {"type": "input_text", "text": "[Candidate generated answer image: score it against the original problem image; do not judge only whether the candidate path itself is connected]"},
            {"type": "input_image", "image_url": image_data_url(candidate_path), "detail": "original"},
        ]
        return openai_pydantic_call(
            client,
            model=args.judge_model,
            reasoning_effort=args.reasoning_effort,
            input_messages=[
                {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                {"role": "user", "content": content},
            ],
            output_model=MazeJudgeResult,
            schema_name="maze_eval",
        )

    def evaluate_one(item: dict[str, Any]) -> dict[str, Any]:
        item_id = str(item["id"])
        started = time.perf_counter()
        generation = generations.get(item_id, {})
        candidate_path = run_dir / "images" / f"{item_id}.png"
        if generation.get("status") != "success" or not candidate_path.is_file():
            return {
                "id": item_id,
                "status": "error",
                "error": "missing successful generation record or candidate image",
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }
        try:
            passes = [
                call_with_retry(
                    lambda: judge_once(item, candidate_path, generation.get("explanation")),
                    max_retries=args.max_retries,
                    base_delay=args.retry_delay,
                )
                for _ in range(args.passes)
            ]
            result = aggregate(passes, args.confidence_threshold)
            return {
                "id": item_id,
                "status": "success",
                "judge_model": args.judge_model,
                **result,
                "latency_seconds": round(time.perf_counter() - started, 3),
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }
        except Exception as exc:
            return {
                "id": item_id,
                "status": "error",
                "error": f"{type(exc).__name__}: {exc}",
                "latency_seconds": round(time.perf_counter() - started, 3),
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }

    total = len(pending)
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        future_map = {executor.submit(evaluate_one, item): item for item in pending}
        completed = 0
        for future in as_completed(future_map):
            row = future.result()
            with write_lock:
                append_jsonl(results_path, row)
                if row.get("needs_human_review"):
                    append_jsonl(review_path, row)
            completed += 1
            print(f"[{completed}/{total}] {row['id']} {row['status']} score={row.get('score')}")

    all_rows = load_jsonl(results_path) if results_path.exists() else []
    write_json(eval_dir / "summary.json", summarize(all_rows))
    print(f"Evaluation complete: {eval_dir}")


if __name__ == "__main__":
    main()
