from __future__ import annotations

import sys
from pathlib import Path as _BootstrapPath
sys.path.insert(0, str(_BootstrapPath(__file__).resolve().parents[1]))

import argparse
import os
import statistics
import threading
import time
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field

from common import (
    append_jsonl,
    call_with_retry,
    image_data_url,
    latest_records,
    load_jsonl,
    openai_pydantic_call,
    select_items,
    write_json,
)


class TangramJudgeResult(BaseModel):
    score: Literal[0, 1, 2, 3]
    uses_all_seven_pieces: bool = False
    piece_shapes_preserved: bool = False
    target_fully_covered: bool = False
    pieces_within_target: bool = False
    no_visible_overlap: bool = False
    lower_tray_cleared: bool = False
    original_canvas_preserved: bool = True
    alternative_valid_solution: bool = False
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    reason: str = ""
    needs_human_review: bool = False
    review_reason: str | None = None


JUDGE_SYSTEM_PROMPT = """You are a strict evaluator for a Tangram visual-reasoning generation benchmark.

You will see three images in a fixed order:
1. The original problem image, with a gray target silhouette at the top and seven colored pieces at the bottom.
2. One known correct reference answer image.
3. The candidate answer image generated by the model.

Core principle: the reference answer is only one known valid arrangement, not the only valid answer. Even if the candidate differs from the reference arrangement, it must be judged fully correct if it uses all seven standard pieces, preserves each piece's shape and size, has no overlap or out-of-bounds placement, and completely fills the target silhouette.

Hard checks:
- All seven pieces must be used, and each piece must be used exactly once.
- The two large triangles are equivalent to each other, and the two small triangles are equivalent to each other; swapping their positions can still be correct.
- Each piece may be translated and rotated, but must not be stretched, compressed, cut, fused, added, or deleted.
- The seven pieces must not visibly overlap, extend outside the target silhouette, or leave obvious gaps.
- The candidate image should preserve the original canvas and target position; after completion, the scattered pieces in the lower tray should be moved away or cleared.
- Minor antialiasing, line-width, or color differences are acceptable, but they must not change geometry.
- Candidate textual explanations are only supporting evidence and cannot compensate for image errors.

Four-level scoring:
3 = Fully correct: all seven pieces are used, shapes and sizes are largely preserved, there is no obvious overlap or out-of-bounds placement, and the target silhouette is fully filled; a legal arrangement different from the reference is allowed.
2 = Mostly correct: the overall arrangement and silhouette are mostly correct, with only a very small local gap, slight out-of-bounds placement, or minor drawing error; no entire piece may be missing or severely deformed.
1 = Partially correct: there is an obvious assembly attempt, but with key gaps, out-of-bounds placement, overlap, missing pieces, deformation, or extensive redrawing/rearrangement that makes legality difficult to verify.
0 = Incorrect: irrelevant output, no assembly, severe errors, unjudgeable result, or obvious fabrication/replacement of pieces.

Output only structured fields and a brief reason. Do not output a long chain of thought."""


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Multimodal-judge evaluation for Tangram generations.")
    p.add_argument("--dataset", type=Path, required=True)
    p.add_argument("--run", type=Path, required=True)
    p.add_argument("--judge-model", default="gpt-5.5")
    p.add_argument("--reasoning-effort", choices=["none", "low", "medium", "high", "xhigh"], default="high")
    p.add_argument("--passes", type=int, default=1)
    p.add_argument("--confidence-threshold", type=float, default=0.72)
    p.add_argument("--start-id", default=None)
    p.add_argument("--end-id", default=None)
    p.add_argument("--ids", default=None)
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--workers", type=int, default=1)
    p.add_argument("--max-retries", type=int, default=3)
    p.add_argument("--retry-delay", type=float, default=2.0)
    p.add_argument("--request-timeout", type=float, default=180.0)
    p.add_argument("--overwrite", action="store_true")
    return p.parse_args()


def aggregate_judges(results: list[TangramJudgeResult], confidence_threshold: float) -> dict[str, Any]:
    scores = [r.score for r in results]
    counts = Counter(scores)
    max_count = max(counts.values())
    raw_score = min(s for s, c in counts.items() if c == max_count)
    representative = next(r for r in results if r.score == raw_score)
    mean_conf = statistics.mean(r.confidence for r in results)
    disagreement = max(scores) - min(scores) if len(scores) > 1 else 0
    fatal = any(
        (not r.uses_all_seven_pieces) or (not r.piece_shapes_preserved) or (not r.original_canvas_preserved)
        for r in results
    )
    final_score = min(raw_score, 1) if fatal else raw_score
    needs_review = (
        mean_conf < confidence_threshold
        or disagreement >= 2
        or any(r.needs_human_review for r in results)
        or any(r.alternative_valid_solution for r in results)
        or fatal
    )
    reasons = [r.review_reason for r in results if r.review_reason]
    if fatal:
        reasons.append("score capped because a judge detected missing/deformed pieces or major canvas drift")
    if disagreement >= 2:
        reasons.append(f"judge score disagreement: {scores}")
    if mean_conf < confidence_threshold:
        reasons.append(f"mean confidence {mean_conf:.2f} below threshold")
    return {
        "score": final_score,
        "normalized_score": round(final_score / 3 * 100, 2),
        "raw_judge_score": raw_score,
        "uses_all_seven_pieces": representative.uses_all_seven_pieces,
        "piece_shapes_preserved": representative.piece_shapes_preserved,
        "target_fully_covered": representative.target_fully_covered,
        "pieces_within_target": representative.pieces_within_target,
        "no_visible_overlap": representative.no_visible_overlap,
        "lower_tray_cleared": representative.lower_tray_cleared,
        "original_canvas_preserved": representative.original_canvas_preserved,
        "alternative_valid_solution": any(r.alternative_valid_solution for r in results),
        "confidence": round(mean_conf, 4),
        "reason": representative.reason,
        "needs_human_review": needs_review,
        "review_reason": "; ".join(dict.fromkeys(reasons)) or None,
        "judge_passes": [r.model_dump() for r in results],
    }


def summarize(rows: list[dict[str, Any]]) -> dict[str, Any]:
    ok = [r for r in rows if r.get("status") == "success"]
    failed = [r for r in rows if r.get("status") != "success"]
    if not ok:
        return {"evaluated_successfully": 0, "evaluation_failures": len(failed)}
    scores = [int(r["score"]) for r in ok]
    dist = Counter(scores)
    by_difficulty: dict[str, dict[str, Any]] = {}
    for difficulty in ("easy", "medium", "hard"):
        subset = [r for r in ok if r.get("difficulty") == difficulty]
        if subset:
            by_difficulty[difficulty] = {
                "count": len(subset),
                "solve_at_1": round(statistics.mean(int(r["score"]) == 3 for r in subset), 6),
                "normalized_score": round(statistics.mean(int(r["score"]) for r in subset) / 3 * 100, 4),
            }
    return {
        "evaluated_successfully": len(ok),
        "evaluation_failures": len(failed),
        "solve_at_1": round(statistics.mean(s == 3 for s in scores), 6),
        "mean_tier": round(statistics.mean(scores), 4),
        "normalized_score": round(statistics.mean(scores) / 3 * 100, 4),
        "score_distribution": {str(k): dist.get(k, 0) for k in [0, 1, 2, 3]},
        "human_review_count": sum(bool(r.get("needs_human_review")) for r in ok),
        "alternative_valid_solution_count": sum(bool(r.get("alternative_valid_solution")) for r in ok),
        "by_difficulty": by_difficulty,
    }


def main() -> None:
    args = parse_args()
    if args.passes < 1 or args.workers < 1:
        raise ValueError("--passes and --workers must be >= 1")
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError("OPENAI_API_KEY is not set")

    try:
        from openai import OpenAI
    except ImportError as exc:
        raise RuntimeError("Install dependencies: pip install -r requirements.txt") from exc
    client = OpenAI(
        **({"base_url": os.environ["OPENAI_BASE_URL"]} if os.getenv("OPENAI_BASE_URL") else {}),
        timeout=args.request_timeout,
    )

    dataset_root = args.dataset.resolve()
    run_dir = args.run.resolve()
    items = load_jsonl(dataset_root / "data.jsonl")
    meta = {str(r["id"]): r for r in load_jsonl(dataset_root / "eval_meta.jsonl")}
    requested_ids = set(args.ids.split(",")) if args.ids else None
    items = select_items(items, args.start_id, args.end_id, requested_ids, args.limit)
    generations = latest_records(run_dir / "records.jsonl")

    eval_dir = run_dir / "evaluation" / f"tangram_{args.judge_model.replace('/', '_')}"
    eval_dir.mkdir(parents=True, exist_ok=True)
    results_path = eval_dir / "results.jsonl"
    review_path = eval_dir / "human_review.jsonl"
    if args.overwrite:
        for p in (results_path, review_path):
            if p.exists():
                p.unlink()
    done = set() if args.overwrite else ({str(r["id"]) for r in load_jsonl(results_path) if r.get("status") == "success"} if results_path.exists() else set())
    pending = [item for item in items if str(item["id"]) not in done]

    write_json(eval_dir / "config.json", {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "dataset": str(dataset_root),
        "run": str(run_dir),
        "judge_model": args.judge_model,
        "judge_mode": "mlm",
        "reasoning_effort": args.reasoning_effort,
        "passes": args.passes,
        "selected_count": len(items),
    })

    lock = threading.Lock()

    def judge_once(item: dict[str, Any], candidate_path: Path, explanation: str | None) -> TangramJudgeResult:
        question = dataset_root / str(item["image"])
        reference = dataset_root / str(item["answer"])
        text = (
            "The following inputs are provided in order: the original tangram problem image, one known correct reference answer, and the candidate answer.\n"
            "The reference answer is not unique; judge whether the candidate itself satisfies the geometric constraints of the seven tangram pieces.\n"
            "Do not rely only on outer-contour similarity; also check whether the interior consists of seven legal standard pieces and whether any piece is missing, fused, deformed, overlapping, out of bounds, or left in the lower tray.\n"
            f"Optional textual description from the candidate: {explanation or '(none)'}"
        )
        return openai_pydantic_call(
            client,
            model=args.judge_model,
            reasoning_effort=args.reasoning_effort,
            input_messages=[
                {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                {"role": "user", "content": [
                    {"type": "input_text", "text": text + "\n[Original problem image]"},
                    {"type": "input_image", "image_url": image_data_url(question), "detail": "original"},
                    {"type": "input_text", "text": "[Known correct reference answer]"},
                    {"type": "input_image", "image_url": image_data_url(reference), "detail": "original"},
                    {"type": "input_text", "text": "[Candidate answer]"},
                    {"type": "input_image", "image_url": image_data_url(candidate_path), "detail": "original"},
                ]},
            ],
            output_model=TangramJudgeResult,
            schema_name="tangram_eval",
        )

    def evaluate_one(item: dict[str, Any]) -> dict[str, Any]:
        item_id = str(item["id"])
        started = time.perf_counter()
        generation = generations.get(item_id, {})
        candidate_path = run_dir / "images" / f"{item_id}.png"
        if generation.get("status") != "success" or not candidate_path.is_file():
            return {"id": item_id, "status": "error", "error": "missing successful generation record or candidate image"}
        if item_id not in meta:
            return {"id": item_id, "status": "error", "error": "missing eval_meta row"}

        try:
            meta_row = meta[item_id]
            explanation = generation.get("explanation")
            judges = [
                call_with_retry(
                    lambda: judge_once(item, candidate_path, explanation),
                    max_retries=args.max_retries,
                    base_delay=args.retry_delay,
                )
                for _ in range(args.passes)
            ]
            result = aggregate_judges(judges, args.confidence_threshold)

            return {
                "id": item_id,
                "status": "success",
                "difficulty": meta_row["difficulty"],
                "judge_source": "mlm",
                **result,
                "latency_seconds": round(time.perf_counter() - started, 3),
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }
        except Exception as exc:
            return {
                "id": item_id,
                "status": "error",
                "error": f"{type(exc).__name__}: {exc}",
                "latency_seconds": round(time.perf_counter() - started, 3),
                "finished_at": datetime.now(timezone.utc).isoformat(),
            }

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {executor.submit(evaluate_one, item): item for item in pending}
        completed = 0
        for future in as_completed(futures):
            row = future.result()
            with lock:
                append_jsonl(results_path, row)
                if row.get("needs_human_review"):
                    append_jsonl(review_path, row)
            completed += 1
            print(f"[{completed}/{len(pending)}] tangram/{row['id']} {row['status']} score={row.get('score')}")

    all_rows = load_jsonl(results_path) if results_path.exists() else []
    write_json(eval_dir / "summary.json", summarize(all_rows))
    print(f"Evaluation finished: {eval_dir}")


if __name__ == "__main__":
    main()
